Controllers/FacultyController.cs
using System.Collections.Generic;
using Common;
using Core.IConfiguration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentWebapp.Models;
using ViewModels;

namespace Controllers
{
    public class FacultyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public FacultyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> List(string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var faculties = await _unitOfWork.Faculty.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                faculties = await _unitOfWork.Faculty.GetAllBy(f => f.FacultyName.Contains(searchString)
                                       || f.Description.Contains(searchString));
            }
            int pageSize = 3;
            return View(PaginatedList<Faculty>.CreateAsync(faculties, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new FacultyViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(FacultyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var faculty = new Faculty
                {
                    FacultyName = model.FacultyName,
                    Description = model.Description
                };
                await _unitOfWork.Faculty.Create(faculty);
                await _unitOfWork.SaveChangesAsync();
                TempData["success"] = "Faculty Created Successfully";
                return RedirectToAction(nameof(List));
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return Content("Faculty Id is null");
            }
            var faculty = await _unitOfWork.Faculty.GetBy(f => f.Id == id);
            if (faculty == null)
            {
                return Content("Faculty Not Found");
            }
            await _unitOfWork.Faculty.Delete(id);
            await _unitOfWork.SaveChangesAsync();
            TempData["success"] = "Faculty Deleted Successfully";
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return Content("Faculty Id is null");
            }
            var faculty = await _unitOfWork.Faculty.GetBy(f => f.Id == id);
            if (faculty == null)
            {
                return Content("Faculty Not Found");
            }
            var facultyModel = new FacultyViewModel()
            {
                Id = faculty.Id,
                FacultyName = faculty.FacultyName,
                Description = faculty.Description,
                InitialFacultyName = faculty.FacultyName
            };
            return View(facultyModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(FacultyViewModel model)
        {
            if (model == null)
            {
                return Content("Faculty Id is null");
            }
            var checkFaculty = await _unitOfWork.Faculty.CheckExistBy(f => f.Id == model.Id);
            if (!checkFaculty)
            {
                return Content("Faculty Not Found");
            }
            var faculty = new Faculty()
            {
                Id = model.Id,
                FacultyName = model.FacultyName,
                Description = model.Description
            };

            await _unitOfWork.Faculty.Edit(faculty);
            await _unitOfWork.SaveChangesAsync();
            TempData["success"] = "Faculty Updated Successfully";
            return RedirectToAction(nameof(List));
        }

        public async Task<IActionResult> VerifyFacultyName(string FacultyName, string InitialFacultyName)
        {
            if (FacultyName == InitialFacultyName)
            {
                return Json(true);
            }

            if (await _unitOfWork.Faculty.CheckExistBy(f => f.FacultyName.ToLower() == FacultyName.ToLower()))
            {
                return Json($"Faculty Name: {FacultyName} already exists!");
            }
            return Json(true);
        }
    }
}

Controllers/SubjectController.cs
using Common;
using Core.IConfiguration;
using Microsoft.AspNetCore.Mvc;
using StudentWebapp.Models;
using ViewModels;

namespace Controllers
{
    public class SubjectController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public SubjectController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> List(string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var subjects = await _unitOfWork.Subject.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                subjects = await _unitOfWork.Subject.GetAllBy(f => f.SubjectName.Contains(searchString)
                                       || f.Description.Contains(searchString));
            }
            int pageSize = 3;
            return View(PaginatedList<Subject>.CreateAsync(subjects, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new SubjectViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                var subject = new Subject
                {
                    SubjectName = model.SubjectName,
                    Description = model.Description
                };
                await _unitOfWork.Subject.Create(subject);
                await _unitOfWork.SaveChangesAsync();
                TempData["success"] = "Subject Created Successfully";
                return RedirectToAction(nameof(List));
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return Content("Subject Id is null");
            }
            var subject = await _unitOfWork.Subject.GetBy(f => f.Id == id);
            if (subject == null)
            {
                return Content("Subject Not Found");
            }
            await _unitOfWork.Subject.Delete(id);
            await _unitOfWork.SaveChangesAsync();
            TempData["success"] = "Subject Deleted Successfully";
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return Content("Subject Id is null");
            }
            var subject = await _unitOfWork.Subject.GetBy(f => f.Id == id);
            if (subject == null)
            {
                return Content("Subject Not Found");
            }
            var subjectModel = new SubjectViewModel()
            {
                Id = subject.Id,
                SubjectName = subject.SubjectName,
                Description = subject.Description,
                InitialSubjectName = subject.SubjectName
            };
            return View(subjectModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SubjectViewModel model)
        {
            if (model == null)
            {
                return Content("Subject Id is null");
            }
            var checkSubject = await _unitOfWork.Subject.CheckExistBy(f => f.Id == model.Id);
            if (!checkSubject)
            {
                return Content("Subject Not Found");
            }
            var subject = new Subject()
            {
                Id = model.Id,
                SubjectName = model.SubjectName,
                Description = model.Description
            };

            await _unitOfWork.Subject.Edit(subject);
            await _unitOfWork.SaveChangesAsync();
            TempData["success"] = "Subject Updated Successfully";
            return RedirectToAction(nameof(List));
        }

        public async Task<IActionResult> VerifySubjectName(string SubjectName, string InitialSubjectName)
        {
            if (SubjectName == InitialSubjectName)
            {
                return Json(true);
            }

            if (await _unitOfWork.Subject.CheckExistBy(f => f.SubjectName.ToLower() == SubjectName.ToLower()))
            {
                return Json($"Subject Name: {SubjectName} already exists!");
            }
            return Json(true);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootswatch.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentWebapp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i
                        class="bi bi-calendar2-heart-fill"></i> Student Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class='nav-link' asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Faculty" asp-action="List">Faculty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Subject" asp-action="List">Subject</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Student Manager
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <partial name="_Notification" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script>
        console.log("I am in")
        toastr.success("@TempData["success"]");
    </script>
}

<script>
    $(document).on('click', '#btn-submit', function (e) {
        console.log('asdf')
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $('form').submit();
            }
        })
    })
</script>